### PR TITLE
Fixes #45 - Flush the final files to send the end event

### LINKED ISSUE #45: [metal-tools-soy] Node process dies after trying to parse more than a specific amount of files in a subfolder
I'm trying to build a Soy project, but I noticed when I try to compile more than 82 files placed in a structure like `src/subfolder`, the `metal-tools-soy` package somehow makes Node process exit prematurely.

The function I used to handle the soy call is like this:
```javascript
const soy = require('metal-tools-soy');

const soyDeps = ['node_modules/metal*/src/**/*.soy'];
const src = ['./src/**/*.soy'];
const dest = ['./soy'];

const buildSoyFiles = (src, dest, soyDeps) => 
  new Promise((resolve, reject) => {
    const handleError = error => reject(error);
    soy({src, dest, soyDeps, handleError}).on('end', () => resolve());
  });

```

This bug is specifically related to trying to compile more than 82 files in a subfolder and using [`src/**/*.soy`](https://github.com/paulocfjunior/metal-tools-soy-limit/blob/master/index.js#L4) glob pattern as `src` on soy options parameter.

If I use `src/subfolder/*.soy`, it works, and if I put all the files in `src` (not in a subfolder), it works too, but in a real project we use many folders (each one with its own subfolders and so on), even if I include each path to the Soy config to compile, the output can't handle the structure properly.

I've made a [project](https://github.com/paulocfjunior/metal-tools-soy-limit) to reproduce this behavior with ease. I created 2 npm scripts:
- `npm run success`, the script [`create.sh`](https://github.com/paulocfjunior/metal-tools-soy-limit/blob/master/create.sh) creates 82 files in `src/child` and [`index.js`](https://github.com/paulocfjunior/metal-tools-soy-limit/blob/master/index.js) calls Soy in a promise, and it resolves successfully.
- `npm run fail`, the script will create 83 files in `src/child`, just as the first one, but `index.js` will not be able to resolve the promise anymore, and it wont reject as well.

I used a flag to verify if the promise either rejected or resolved, any of those would change the flag, but at the end of the fail case, the flag is still unchanged.
**The program simply dies, and kill the whole node process, with no error.**

-----
PS:
- I used just elementary templates, with the bare minimum content to be a template;
- I cleaned up all the source and compiled files before the tests;
- Tested on Ubuntu and Mac OS.

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by ygorcosta** [comment]
@ipeychev @matuzalemsteles @jbalsas 
any plans to merge?

**Comment by jbalsas** [comment]
Hey @ygorcosta, sorry, we still had some failing tests here, so wasn't really sure to merge it... @matuzalemsteles , do you think this is safe to merge? Also, @ygorcosta, which `metal-tools-soy` version are you using? I'd guess you're on `4.x`, so we'd probably prefer to send this to `4.x`.

**Comment by ygorcosta** [comment]
@jbalsas ok, thank you! 
we are using `4.2.9` to be more exactly =)

**Comment by matuzalemsteles** [comment]
hey @jbalsas, yes this is safe, the tests are going locally, it is giving some problems with the tests in the CI, I still have to investigate more thoroughly to verify the problem. Before giving merged, try running the tests locally for security...

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, I tried to change the base, but it gives conflicts... could you please adapt this so we can target the `4.x` branch and cut a release?

Thanks!

**Comment by jbalsas** [comment]
I've rebased this on top of `4.x` and sent to https://github.com/metal/metal-tools-soy/pull/53

**Pull request closed without merging**
