### PR TITLE
Moving the Soy tooling repositories

### PR DESCRIPTION
**Pull request by matuzalemsteles**
hey @jbalsas, I moved the repositories which is listed in #35 to here and making that repo a monorepo with lerna. I have removed some files from the packages to centralize the root folder so it can be easier to maintain and I also configured the CircleCI, I want to test to see the benefits of it, seem to be very interesting.

When you can take a look at the rules of eslint I will be grateful. I had to disable some not to change all at hand, but we can adjust this...

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, thanks a lot for putting this together!!! 👏 

I'd like to avoid having CircleCI here if possible. I'd rather stick to our current Travis setup on complex and heavily relied upon repos like this one. Otherwise, switching from one project to other becomes a very complex task. Imagine switching from AlloyEditor to Clay to Senna to Metal.js and then here and all having different configurations and workflows.

Do you mind trying that on a different, more isolated repo or a separate branch of this one?

Thanks! :)

**Comment by matuzalemsteles** [comment]
Hey @jbalsas, Thanks! Sure, no problem. Thank you very much for your vision.

**Comment by matuzalemsteles** [comment]
hey @jbalsas, I think this is ready to go now.

**Comment by jbalsas** [comment]
Awesome, @matuzalemsteles! 

Could you please, do me the favour of sending a [PR like this one](https://github.com/liferay/liferay-theme-tasks/commit/c3a0721eed9007380bf916b918cc349273582089) to those repos so we can update their readmes and archive them properly?

Thanks, great job! 👏

**Comment by matuzalemsteles** [comment]
Sure, np. Thanks!!

**Comment by matuzalemsteles** [comment]
hey @jbalsas, Send a pr to all the repositories we've moved and the [generate-soy-source-maps](https://github.com/matuzalemsteles/generate-soy-source-maps) repo has already been archived.

* [soyparser](https://github.com/metal/soyparser/pull/5)
* [metal-soy-critic](https://github.com/metal/metal-soy-critic/pull/15)
* [metal-soy-loader](https://github.com/metal/metal-soy-loader/pull/8)
* [gulp-soynode](https://github.com/metal/gulp-soynode/pull/15)

**Comment by jbalsas** [comment]
Great, I've merged and archived them all.

I've also transferred all open issues to this repo so we can pick them up in the future! 💪

**Pull request merged**
