### PR TITLE
Enable stand alone command line use of tool

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, for the sake of documentation... can you update the `Readme.md` with usage instructions before we merge it in? 😉

**Comment by robframpton** [comment]
@jbalsas yep, no problem.

**Review by jbalsas — CHANGES_REQUESTED** [review]
Hey @Robert-Frampton, for the sake of documentation... can you update the `Readme.md` with usage instructions before we merge it in? 😉

**Comment by robframpton** [comment]
Hey @jbalsas 

I added some basic information on installation, usage, and available options. I think on metaljs.com we should add more detailed instructions on how to use in conjunction with babel.

**Pull request merged**
