### PR TITLE
Updates prettier and extracts configuration to prettierrc

### PR DESCRIPTION
**Pull request by jbalsas**
This PR updates `SoyToIncrementalDomSrcCompiler` to https://github.com/google/closure-templates/commit/6a6a54ff55e1ab6e09dd24703825d5971f450eaa

The only change in output is apparent in https://github.com/metal/metal-tools-soy/pull/23/commits/6ba052dec316cc7ec8d573aab46e27018d33e10d

```
*/
 -  function $render(opt_data, opt_ijData, opt_ijData_deprecated) {
 +  var $render = function(opt_data, opt_ijData, opt_ijData_deprecated) {
      [...]
 -  }
 +  };
exports.render = $render;
```

I've tested it in the `metal.js` project and all looks good as well.

Some interesting things in this last batch of work from Google:
- [Add some honesty to our readme](https://github.com/google/closure-templates/commit/b3cb7780c8e5377c662cff758bc86ce9663c9c67)
- [Produce a single JS file with all closure deps required by the Soy runtime](https://github.com/google/closure-templates/commit/2aa6e7ab5d72282ca23071b70c29e805ec43ff44): this could replace our custom build in `metal-soy-bundle` (actually, not that simple because it doesn't include `goog.loadModule` which we have pushed to our compiled templates 😢)

What do you think, @eduardolundgren, @Robert-Frampton, @brunobasto?

### CODE REVIEW

**Review by robframpton — APPROVED** [review]

**Comment by robframpton** [comment]
Do you think we should be concerned about their lack of support? Seems like we're betting a lot on our soy infrastructure in Portal, it would be a shame to find ourselves in a YUI situation again.

**Comment by jbalsas** [comment]
I think it's reassuring to know that they are heavily invested in it, just understaffed for the open source release...

**Comment by brunobasto** [comment]
I think it's both reassuring and little concerning.
> Closure Templates is widely used and well maintained internally at Google

Makes me think it's be pretty stable and will be around for a while.

> does not currently have staffing to support the open source release

Makes me think fixpacks may take a while and will be unpredictable.

**Review by brunobasto — APPROVED** [review]

**Comment by mthadley** [comment]
It also means they will most likely focus on their own needs and priorities, and won't be looking much at the community.  I'm wondering what "widely used" means, as well. Does it mean that they just have a lot of legacy code? Or are they actively working on new features using soy.

**Pull request merged**
